README.md

Hello, first of all, thanks for your work on this gem!
I've been trying to get Google Authenticator to display a title just as it's common when setting up 2-step authentication services. Since I didn't find any documentation about it I had to dig into the codebase and discover the `opts[:issuer]` so hopefully this PR will make it slightly easier to people to add this functionality.
I've attached a couple of screenshots that clarify my original intent.
**Without issuer**
**With an issuer**

Mention TOTP issuer option

---

lib/rotp/otp.rb

the private method is already called above in the class definition, so rm duplicate

remove duplicate private call from the class

---

lib/rotp/totp.rb

See https://gitlab.com/gitlab-org/gitlab-ce/issues/1679.
Apparently the Windows Phone Authenticator app only recognizes the provisioning URL when the issuer comes _after_ the secret. Bad coding on the Windows Phone app's part, I guess, but it's easier to change this in rotp than it is to change it in the app.

Reverse order of secret and issuer params in provisioning URL.

---

lib/rotp/base32.rb
lib/rotp/otp.rb

These changes are the minimal ones necessary to allow Rodauth's specs
to pass. There may well be other changes that are required.

Work with ruby 2.3's --enable-frozen-string-literal

---

lib/rotp/totp.rb
spec/lib/rotp/totp_spec.rb

According the google authenticator docs the issuer should be
included both in the URL itself as well as in the query
string. See:
https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer

Include issuer in TOTP provisioning URL as well as query string

---

lib/rotp.rb
lib/rotp/base32.rb

SecureRandom uses OpenSSL::Random under the hood anyway but
is apparently a more secure:
https://bugs.ruby-lang.org/issues/4579

Use SecureRandom rather than OpenSSL::Random

---

lib/rotp/hotp.rb
lib/rotp/otp.rb
lib/rotp/totp.rb
spec/lib/rotp/hotp_spec.rb
spec/lib/rotp/totp_spec.rb

Include the digits paramater in the URI generated
by #provisioning_uri when #digits is a non-default
value.  Add tests for this for totp and hotp for
default and non-default number of digits.

Add digits paramater to provisioning URI

---

lib/rotp/totp.rb
spec/lib/rotp/totp_spec.rb

This allows a user to store the result of the verify for use in
subsequent checks to ensure that token codes are neither reused
nor used out of order.

Add totp verify that accepts and returns time int

---

lib/rotp/totp.rb
spec/lib/rotp/totp_spec.rb

Include the digest as algorithm parameter in URI returned by TOTP#provisioning_uri
closes mdp/rotp#61

Include the digest as algorithm parameter

---

lib/rotp.rb

Apparently in ruby 2.5.0 openssl has to be required explicity to avoid the following exception. This commit introduces that.
```ruby
.../lib/rotp/otp.rb:25:in `generate_otp': uninitialized constant ROTP::OTP::OpenSSL (NameError)```

Require Openssl to fix usage with ruby 2.5.

---

lib/rotp/base32.rb
spec/lib/rotp/base32_spec.rb

Some services will pad the base32 string with `=` signs.
ROTP will throw an error if it sees any equal signs in a base32 string.
This PR fixes that.

Allow decoding base32 with padding

---

lib/rotp/otp.rb
lib/rotp/totp.rb
spec/lib/rotp/totp_spec.rb

Hey guys,
we encountered an infinite loop by mistake. The params passed to `verify_with_drift` (https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L43) had `time` as `nil` and `drift` as a positive integer.  As the result, the ranges produced a negative number. `int_to_bytestring` has an does a 8 bit shift of the value passed to it. However, if it's a negative number, it goes into the infinite loop.
Although a developer must provide valid input, there could be time of mistakes like we did. I believe that by providing additional validation to this case, we can quickly pin-point a developer where the invalid input is.

Additional check for negative numbers in #int_to_bytestring

---

rotp.gemspec

The RubyGems property rubyforge_project is removed without a replacement.

gemspec: Drop EOL'd rubyforge_project property

---

README.md
lib/rotp/totp.rb
spec/lib/rotp/totp_spec.rb

https://github.com/google/google-authenticator/wiki/Key-Uri-Format

URI encode the issuer parameter value

---

docker-compose.yml
lib/rotp.rb
lib/rotp/base32.rb
lib/rotp/hotp.rb
lib/rotp/otp.rb
lib/rotp/otp/uri.rb
lib/rotp/totp.rb
rotp.gemspec
spec/lib/rotp/hotp_spec.rb
spec/lib/rotp/otp/uri_spec.rb
spec/lib/rotp/totp_spec.rb

Resolves https://github.com/mdp/rotp/issues/98
Working with the v5.1.0 release we had a workaround for spaces encoded as `+` in issuer values. We couldn't upgrade to the v6.0.0 release because of the double encoding bug. Looking over https://github.com/google/google-authenticator/wiki/Key-Uri-Format I felt it was sufficiently awkward enough to warrant it's own home to contain all the non-standard munging.
I added `docker-compose.yml` to assist with testing across all versions.
```
$ docker-compose up
```

Introducing ROTP::OTP::URI

---

rotp.gemspec

This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/rotp or some tools or APIs that use the gem's metadata.

GitHub is HTTPS by default

---

CHANGELOG.md
Dockerfile-3.0-rc
docker-compose.yml
lib/rotp/version.rb
rotp.gemspec

- Update to allow for usage in project on Ruby >= 3.0
- Update Dockerfile tests
- Bump to 6.2.0

Allow for Ruby 3.0

---

CHANGELOG.md

Addresses breaking changes from https://github.com/mdp/rotp/pull/63

Update CHANGELOG with Breaking Changes in Version 4 upgrade

---

lib/rotp/otp.rb

I just found an outdated comment and removed it.
The `padding` option is unavailable since https://github.com/mdp/rotp/commit/db7cd995b5eecc2ae0038731efad970e6a3235b5#diff-55ac3d4d2ca19a86c547e261d8af1fb6a7f06333865c2d5e5987b90faebe192cL24 .

Remove obsolete comment

---

Dockerfile-3.0
docker-compose.yml

This prepares to add new stable Ruby versions.
Moved from #121 since it's not possible to rebase with changes to .github/workflows for security reasons.

chore: docker-compose.yml: Use ruby-3.0

---

.github/workflows/release.yaml

- Can't publish to Rubygems via CD with MFA currently, just append the files to the release tag.

chore: Add the .gem file to release for easier publishing
